# Dependabot will run on day 16 of each month at 02:27 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '27 2 16 * *'
    open-pull-requests-limit: 15
    versioning-strategy: 'increase'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '27 2 16 * *'
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    open-pull-requests-limit: 15
